CREATE TABLE IF NOT EXISTS stats
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT stats_pk PRIMARY KEY,
    APP       varchar,
    URI       varchar,
    IP        varchar,
    TIMESTAMP timestamp
);